import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Guard rails for **credentials**: a secret in the repository is also a secret
/// in every binary built from it, so none may ever be committed.
///
/// Two were, and this file exists because nothing checked: `api_key_pool.dart`
/// carried a live OpenRouter key and a live **metered** Azure Speech key as
/// "fallback" literals (removed 2026-09-26; both now return `'MISSING_KEY'`).
/// Nothing in the toolchain objected, which is the whole problem with a leak.
///
/// The rules are **format-based, not entropy-based**, on purpose: `lib/` is full
/// of legitimately long strings (AI prompt templates), so a "long literal" rule
/// would drown in false positives and be switched off within a week.
List<String> _libSources() => Directory('lib')
    .listSync(recursive: true)
    .whereType<File>()
    .where((File file) => file.path.endsWith('.dart'))
    .map((File file) => file.path.replaceAll(r'\', '/'))
    .toList();

void main() {
  group('Secret guard rails', () {
    test('no OpenRouter / OpenAI style secret is committed', () {
      final List<String> offenders = <String>[];
      final RegExp secret = RegExp(r'sk-[A-Za-z0-9\-_]{20,}');
      for (final String path in _libSources()) {
        for (final RegExpMatch match
            in secret.allMatches(File(path).readAsStringSync())) {
          offenders.add('$path: ${match.group(0)!.substring(0, 12)}…');
        }
      }
      expect(
        offenders,
        isEmpty,
        reason: 'A key-shaped literal is committed to lib/. Rotate it as well as '
            'deleting it - it is already in the history: $offenders',
      );
    });

    test('no Google API key is committed outside the generated Firebase options',
        () {
      // `firebase_options.dart` is generated by the FlutterFire CLI, and its
      // `AIzaSy…` values are project *identifiers* designed to be public:
      // security comes from Firestore rules and App Check, not from hiding them.
      // Everywhere else, an `AIzaSy…` literal is a real key (Gemini keys share
      // the format) and is refused.
      final List<String> offenders = <String>[];
      final RegExp googleKey = RegExp(r'AIzaSy[A-Za-z0-9_\-]{33}');
      for (final String path in _libSources()) {
        if (path.endsWith('firebase_options.dart')) continue;
        for (final RegExpMatch match
            in googleKey.allMatches(File(path).readAsStringSync())) {
          offenders.add('$path: ${match.group(0)!.substring(0, 10)}…');
        }
      }
      expect(offenders, isEmpty, reason: 'Google API key literal found: $offenders');
    });

    test('the key pool holds no long literal at all', () {
      // This one file may hold no credential, so the rule can be that strict.
      // The threshold is 28 characters: the longest legitimate literal in the
      // file is `goog_YOUR_GOOGLE_KEY_HERE` (26), and the two literals that had
      // to be deleted were 73 and 85, so nothing real can hide underneath.
      final File file = File('lib/core/services/api_key_pool.dart');
      final List<String> offenders = <String>[];
      // `[^'\n]`, not `[^']`: a pattern that may cross a newline happily spans
      // unrelated code between two innocent apostrophes and invents offenders.
      // A credential is always one line, so one line is all the rule needs.
      for (final RegExpMatch match
          in RegExp(r"'([^'\n]{28,})'").allMatches(file.readAsStringSync())) {
        final String literal = match.group(1)!;
        // RevenueCat's `appl_` / `goog_` values are publishable SDK keys by
        // design; they identify an app and are not secrets.
        if (literal.startsWith('appl_') || literal.startsWith('goog_')) continue;
        // Import paths (`package:flutter_riverpod/flutter_riverpod.dart`) are
        // legitimate long literals, so skip anything that looks like a URI or a
        // path; a credential contains no slash.
        if (literal.contains('/') ||
            literal.startsWith('package:') ||
            literal.startsWith('dart:')) {
          continue;
        }
        offenders.add('${literal.substring(0, 12)}… (${literal.length} chars)');
      }
      expect(
        offenders,
        isEmpty,
        reason: 'api_key_pool.dart is not a place for long literals - a '
            'credential belongs in --dart-define or .env, never in source: '
            '$offenders',
      );
    });
  });
}
