// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApKJBVXf4b-o9DBCItzCOolwa3GpxWIj4',
    appId: '1:168461209502:web:df913609b33c558783108f',
    messagingSenderId: '168461209502',
    projectId: 'hanzi-master-bcef9',
    authDomain: 'hanzi-master-bcef9.firebaseapp.com',
    storageBucket: 'hanzi-master-bcef9.firebasestorage.app',
    measurementId: 'G-F2GB7CK5T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYuC7Y5vJklmM0xDxSWIsUcCeg8K9JanQ',
    appId: '1:168461209502:android:0d8e3bbef9eea12a83108f',
    messagingSenderId: '168461209502',
    projectId: 'hanzi-master-bcef9',
    storageBucket: 'hanzi-master-bcef9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EWtkITxlJ3qUE1W2hrVe9pIWIsh6r7s',
    appId: '1:168461209502:ios:7d8785d933c3705583108f',
    messagingSenderId: '168461209502',
    projectId: 'hanzi-master-bcef9',
    storageBucket: 'hanzi-master-bcef9.firebasestorage.app',
    iosClientId: '168461209502-3il6a2r77i4qtb35osobao250mcb6u97.apps.googleusercontent.com',
    iosBundleId: 'com.sinospark.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8EWtkITxlJ3qUE1W2hrVe9pIWIsh6r7s',
    appId: '1:168461209502:ios:ff3c8f4f07a70e5083108f',
    messagingSenderId: '168461209502',
    projectId: 'hanzi-master-bcef9',
    storageBucket: 'hanzi-master-bcef9.firebasestorage.app',
    iosClientId: '168461209502-1uvlgno23pd2g0rreq59n97rs3ka6h9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanziMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApKJBVXf4b-o9DBCItzCOolwa3GpxWIj4',
    appId: '1:168461209502:web:73a9a25fa396601683108f',
    messagingSenderId: '168461209502',
    projectId: 'hanzi-master-bcef9',
    authDomain: 'hanzi-master-bcef9.firebaseapp.com',
    storageBucket: 'hanzi-master-bcef9.firebasestorage.app',
    measurementId: 'G-VW0ZFG6PDF',
  );
}
