import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import '../domain/models/video_transcript.dart';

final youtubeRepositoryProvider = Provider<YoutubeRepository>((ref) {
  return YoutubeRepository();
});

class YoutubeRepository {
  final YoutubeExplode _yt = YoutubeExplode();

  // In-memory cache: query → results with timestamp
  static final Map<String, _CachedResult> _cache = {};
  static const _cacheTtl = Duration(minutes: 5);
  static const _ccManifestTimeout = Duration(seconds: 4);

  Future<List<Video>> searchVideos(String query) async {
    // Check cache first
    final cached = _cache[query];
    if (cached != null && DateTime.now().difference(cached.timestamp) < _cacheTtl) {
      debugPrint('[YT Cache] Hit for "$query" → ${cached.videos.length} videos');
      return cached.videos;
    }

    final validVideos = <Video>[];
    try {
      final searchQuery = '$query 中文, cc';
      final results = await _yt.search.search(searchQuery);

      final iterator = results.iterator;
      int processedCount = 0;

      while (processedCount < 20) {
        Video video;
        try {
          if (!iterator.moveNext()) {
            break;
          }
          video = iterator.current;
        } catch (e) {
          debugPrint('Error parsing search result item: $e');
          continue;
        }

        processedCount++;

        // Only gate: must have Chinese closed captions (with timeout)
        try {
          final manifest = await _yt.videos.closedCaptions
              .getManifest(video.id)
              .timeout(_ccManifestTimeout);
          final hasChinese =
              manifest.tracks.any((t) => t.language.code.startsWith('zh'));
          if (!hasChinese) continue;
        } catch (_) {
          // No closed captions, timeout, or error — skip this video
          continue;
        }

        validVideos.add(video);

        // Stop early if we have enough results
        if (validVideos.length >= 10) break;
      }
    } catch (e) {
      debugPrint('Error searching videos for query $query: $e');
    }

    // Cache the result
    _cache[query] = _CachedResult(
      videos: validVideos,
      timestamp: DateTime.now(),
    );
    debugPrint('[YT Cache] Stored "${query}" → ${validVideos.length} videos');

    return validVideos;
  }

  Future<VideoTranscript?> getTranscript(String videoId) async {
    try {
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);

      final tracks = manifest.tracks;
      if (tracks.isEmpty) return null;

      // Log all available tracks for debugging
      for (final t in tracks) {
        debugPrint('[CC Track] lang=${t.language.code} format=${t.format.formatCode} autoGen=${t.isAutoGenerated}');
      }

      // Priority order: prefer actual Hanzi tracks over auto-generated Pinyin tracks.
      // YouTube auto-generated Chinese captions come in Pinyin (Latin alphabet).
      // The `isAutoGenerated` flag tells us exactly which ones to deprioritize.
      ClosedCaptionTrackInfo? trackInfo;

      // 1. Prefer a MANUAL (not auto-generated) zh track — these contain real Hanzi
      trackInfo = tracks.where((t) =>
        t.language.code.startsWith('zh') && !t.isAutoGenerated
      ).firstOrNull;

      // 2. Fallback: any zh track (may be auto-generated Pinyin, Gemini will convert)
      trackInfo ??= tracks.where((t) => t.language.code.startsWith('zh')).firstOrNull;

      // 3. Fallback: English
      trackInfo ??= tracks.where((t) => t.language.code.startsWith('en')).firstOrNull;

      // 4. Last resort: first available
      trackInfo ??= tracks.first;

      debugPrint('[CC] Selected: lang=${trackInfo.language.code} format=${trackInfo.format.formatCode} autoGen=${trackInfo.isAutoGenerated}');

      final track = await _yt.videos.closedCaptions.get(trackInfo);

      // Detect if the captions are Pinyin (Latin alphabet) or real Hanzi
      final isHanziTrack = track.captions.any((c) => RegExp(r'[\u4e00-\u9fff]').hasMatch(c.text));
      debugPrint('[CC] isHanziTrack=$isHanziTrack, total captions=${track.captions.length}');

      final lines = track.captions.map((c) => TranscriptLine(
        text: c.text,
        // If the captions are Pinyin, store them in the pinyin field immediately
        pinyin: isHanziTrack ? null : c.text,
        start: c.offset,
        duration: c.duration,
      )).toList();

      return VideoTranscript(videoId: videoId, lines: lines);
    } catch (e) {
      debugPrint('Error fetching transcript: $e');
      return null;
    }
  }

  void dispose() {
    _yt.close();
  }
}

class _CachedResult {
  final List<Video> videos;
  final DateTime timestamp;
  _CachedResult({required this.videos, required this.timestamp});
}
