import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import '../domain/models/youtube_video.dart';
import '../domain/models/video_transcript.dart';

final youtubeRepositoryProvider = Provider<YoutubeRepository>((ref) {
  return YoutubeRepository();
});

class YoutubeRepository {
  YoutubeRepository();

  // In-memory cache: query → results with timestamp
  static final Map<String, _CachedResult> _cache = {};
  static const _cacheTtl = Duration(minutes: 10);

  // Cache for hasChineseCaptions results
  static final Map<String, _CachedBool> _captionCheckCache = {};
  static const _captionCheckCacheTtl = Duration(hours: 1);

  // Transcript cache
  static final Map<String, _CachedTranscript> _transcriptCache = {};
  static const _transcriptCacheTtl = Duration(hours: 1);

  /// Creates a fresh YoutubeExplode instance.
  YoutubeExplode _createYoutubeExplode() => YoutubeExplode();

  /// Searches YouTube for videos matching [query] that have softcoded Chinese subtitles.
  Future<List<YoutubeVideo>> searchVideos(String query) async {
    // Check cache first
    final cached = _cache[query];
    if (cached != null &&
        DateTime.now().difference(cached.timestamp) < _cacheTtl) {
      debugPrint(
          '[YT Cache] Hit for "$query" → ${cached.videos.length} videos');
      return cached.videos;
    }

    final videos = <YoutubeVideo>[];

    try {
      final yt = _createYoutubeExplode();
      try {
        final searchList = await yt.search.search(query);
        final rawVideos = <Video>[];
        for (final video in searchList) {
          rawVideos.add(video);
          if (rawVideos.length >= 25) break;
        }

        // Add all found YouTube search results to ensure the category feed is immediately populated
        for (final rawVideo in rawVideos) {
          videos.add(_videoToModel(rawVideo));
          if (videos.length >= 15) break;
        }
      } finally {
        yt.close();
      }

      debugPrint('[YT Explode Search] Found ${videos.length} videos for "$query"');
    } catch (e) {
      debugPrint('[YT Explode Search] Error: $e');
    }

    if (videos.isNotEmpty) {
      _cache[query] = _CachedResult(
        videos: videos,
        timestamp: DateTime.now(),
      );
    }

    return videos;
  }

  /// Converts a youtube_explode_dart [Video] to our [YoutubeVideo] domain model.
  YoutubeVideo _videoToModel(Video video) {
    String thumb = video.thumbnails.highResUrl;
    if (thumb.isEmpty) {
      thumb = video.thumbnails.mediumResUrl;
    }
    if (thumb.isEmpty) {
      thumb = 'https://img.youtube.com/vi/${video.id.value}/hqdefault.jpg';
    }

    return YoutubeVideo(
      id: video.id.value,
      title: video.title,
      url: 'https://www.youtube.com/watch?v=${video.id.value}',
      duration: video.duration,
      mediumThumbnailUrl: thumb,
      highThumbnailUrl: thumb,
      uploadDate: video.publishDate,
      channelTitle: video.author,
    );
  }



  /// Lightweight check: returns true if the video has Chinese captions.
  Future<bool> hasChineseCaptions(String videoId) async {
    try {
      final cached = _captionCheckCache[videoId];
      if (cached != null &&
          DateTime.now().difference(cached.timestamp) < _captionCheckCacheTtl) {
        return cached.value;
      }

      final yt = _createYoutubeExplode();
      try {
        final manifest = await yt.videos.closedCaptions.getManifest(videoId);
        final hasChinese =
            manifest.tracks.any((t) => _isChineseLanguage(t.language.code));

        _captionCheckCache[videoId] = _CachedBool(
          value: hasChinese,
          timestamp: DateTime.now(),
        );

        debugPrint('[YT hasCaptions] $videoId → $hasChinese');
        return hasChinese;
      } finally {
        yt.close();
      }
    } catch (e) {
      debugPrint('[YT hasChineseCaptions] Error for $videoId: $e');
      return false;
    }
  }

  /// Fetches the transcript (closed captions) for a YouTube video.
  Future<VideoTranscript?> getTranscript(String videoId) async {
    try {
      final cached = _transcriptCache[videoId];
      if (cached != null &&
          DateTime.now().difference(cached.timestamp) < _transcriptCacheTtl) {
        debugPrint(
            '[YT Transcript] Cache hit for $videoId ${cached.transcript.lines.length} lines');
        return cached.transcript;
      }

      final yt = _createYoutubeExplode();
      try {
        final manifest = await yt.videos.closedCaptions.getManifest(videoId);

        // Look for Chinese tracks first (prefer manual over auto-generated)
        ClosedCaptionTrackInfo? bestTrack;
        for (final track in manifest.tracks) {
          if (_isChineseLanguage(track.language.code)) {
            if (!track.isAutoGenerated) {
              bestTrack = track;
              break;
            }
            bestTrack ??= track;
          }
        }

        // If no Chinese CC track exists, fall back to any available CC track (e.g. English / original)
        if (bestTrack == null && manifest.tracks.isNotEmpty) {
          bestTrack = manifest.tracks.firstWhere(
            (t) => !t.isAutoGenerated,
            orElse: () => manifest.tracks.first,
          );
        }

        if (bestTrack == null) {
          debugPrint('[YT Transcript] No caption tracks available for $videoId');
          return null;
        }

        final captionTrack = await yt.videos.closedCaptions.get(bestTrack);
        final lines = <TranscriptLine>[];

        for (final caption in captionTrack.captions) {
          final text = caption.text.trim();
          if (text.isEmpty) continue;
          lines.add(TranscriptLine(
            text: text,
            start: caption.offset,
            duration: caption.duration,
          ));
        }

        if (lines.isEmpty) {
          debugPrint('[YT Transcript] Empty captions for $videoId');
          return null;
        }

        final transcript = VideoTranscript(videoId: videoId, lines: lines);
        _transcriptCache[videoId] = _CachedTranscript(
          transcript: transcript,
          timestamp: DateTime.now(),
        );

        debugPrint('[YT Transcript] Success: $videoId → ${lines.length} lines');
        return transcript;
      } finally {
        yt.close();
      }
    } catch (e) {
      debugPrint('[YT Transcript] Error for $videoId: $e');
      return null;
    }
  }

  // ── Channel cache ──
  static final Map<String, _CachedChannel> _channelCache = {};
  static const _channelCacheTtl = Duration(hours: 1);

  // ── Channel uploads cache ──
  static final Map<String, _CachedResult> _channelUploadsCache = {};

  /// Gets channel metadata by @handle.
  Future<Map<String, String>> getChannelByHandle(String handle) async {
    final cacheKey = 'handle:$handle';
    final cached = _channelCache[cacheKey];
    if (cached != null &&
        DateTime.now().difference(cached.timestamp) < _channelCacheTtl) {
      return cached.data;
    }

    final yt = _createYoutubeExplode();
    try {
      final channel = await yt.channels.getByHandle(handle);
      final data = {
        'id': channel.id.value,
        'title': channel.title,
        'logoUrl': channel.logoUrl,
      };
      _channelCache[cacheKey] = _CachedChannel(
        data: data,
        timestamp: DateTime.now(),
      );
      debugPrint('[YT Channel] Resolved handle "$handle" → ${channel.title}');
      return data;
    } catch (e) {
      debugPrint('[YT Channel] Error resolving handle "$handle": $e');
      rethrow;
    } finally {
      yt.close();
    }
  }

  /// Gets channel metadata by channel ID (UC...).
  Future<Map<String, String>> getChannelById(String channelId) async {
    final cacheKey = 'id:$channelId';
    final cached = _channelCache[cacheKey];
    if (cached != null &&
        DateTime.now().difference(cached.timestamp) < _channelCacheTtl) {
      return cached.data;
    }

    final yt = _createYoutubeExplode();
    try {
      final channel = await yt.channels.get(channelId);
      final data = {
        'id': channel.id.value,
        'title': channel.title,
        'logoUrl': channel.logoUrl,
      };
      _channelCache[cacheKey] = _CachedChannel(
        data: data,
        timestamp: DateTime.now(),
      );
      debugPrint('[YT Channel] Resolved id "$channelId" → ${channel.title}');
      return data;
    } catch (e) {
      debugPrint('[YT Channel] Error resolving id "$channelId": $e');
      rethrow;
    } finally {
      yt.close();
    }
  }

  /// Gets channel metadata by discovering which channel uploaded a video.
  Future<Map<String, String>> getChannelByVideo(String videoId) async {
    final cacheKey = 'video:$videoId';
    final cached = _channelCache[cacheKey];
    if (cached != null &&
        DateTime.now().difference(cached.timestamp) < _channelCacheTtl) {
      return cached.data;
    }

    final yt = _createYoutubeExplode();
    try {
      final channel = await yt.channels.getByVideo(videoId);
      final data = {
        'id': channel.id.value,
        'title': channel.title,
        'logoUrl': channel.logoUrl,
      };
      _channelCache[cacheKey] = _CachedChannel(
        data: data,
        timestamp: DateTime.now(),
      );
      debugPrint('[YT Channel] Resolved video "$videoId" → ${channel.title}');
      return data;
    } catch (e) {
      debugPrint('[YT Channel] Error resolving video "$videoId": $e');
      rethrow;
    } finally {
      yt.close();
    }
  }

  /// Fetches recent uploads from a channel.
  /// Returns up to [maxPages] × 30 videos (capped at [maxVideos]).
  Future<List<YoutubeVideo>> getChannelUploads(String channelId,
      {int maxPages = 3, int maxVideos = 120, String? channelName}) async {
    final cacheKey = 'uploads:$channelId:$maxPages';
    final cached = _channelUploadsCache[cacheKey];
    if (cached != null &&
        DateTime.now().difference(cached.timestamp) < _cacheTtl) {
      debugPrint(
          '[YT ChUploads] Cache hit for "$channelId" → ${cached.videos.length} videos');
      return cached.videos;
    }

    final videos = <YoutubeVideo>[];
    final yt = _createYoutubeExplode();

    try {
      try {
        final uploads = await yt.channels.getUploadsFromPage(channelId);
        var page = 1;
        var current = uploads;
        while (true) {
          for (final video in current) {
            videos.add(YoutubeVideo(
              id: video.id.value,
              title: video.title,
              url: 'https://www.youtube.com/watch?v=${video.id.value}',
              duration: video.duration,
              mediumThumbnailUrl: video.thumbnails.mediumResUrl,
              highThumbnailUrl: video.thumbnails.maxResUrl.isNotEmpty
                  ? video.thumbnails.maxResUrl
                  : video.thumbnails.mediumResUrl,
              uploadDate: video.publishDate,
              channelTitle: video.author,
            ));
          }

          if (page >= maxPages || videos.length >= maxVideos) break;

          final next = await current.nextPage();
          if (next == null) break;
          current = next;
          page++;
        }
      } catch (e) {
        debugPrint('[YT ChUploads] getUploadsFromPage failed for $channelId ($e), falling back to channel query');
        // Fallback: search by channel ID or channel name
        final searchQuery = channelName != null && channelName.isNotEmpty
            ? channelName
            : channelId;
        final searchResults = await yt.search.search(searchQuery);
        for (final video in searchResults) {
          videos.add(_videoToModel(video));
          if (videos.length >= maxVideos) break;
        }
      }

      _channelUploadsCache[cacheKey] = _CachedResult(
        videos: videos,
        timestamp: DateTime.now(),
      );
      debugPrint(
          '[YT ChUploads] Loaded ${videos.length} videos for "$channelId"');
      return videos;
    } catch (e) {
      debugPrint('[YT ChUploads] Error for "$channelId": $e');
      rethrow;
    } finally {
      yt.close();
    }
  }

  bool _isChineseLanguage(String langCode) {
    final lower = langCode.toLowerCase();
    return lower.startsWith('zh') || lower == 'cmn' || lower == 'yue';
  }
}

class _CachedResult {
  final List<YoutubeVideo> videos;
  final DateTime timestamp;
  _CachedResult({required this.videos, required this.timestamp});
}

class _CachedTranscript {
  final VideoTranscript transcript;
  final DateTime timestamp;
  _CachedTranscript({required this.transcript, required this.timestamp});
}

class _CachedBool {
  final bool value;
  final DateTime timestamp;
  _CachedBool({required this.value, required this.timestamp});
}

class _CachedChannel {
  final Map<String, String> data;
  final DateTime timestamp;
  _CachedChannel({required this.data, required this.timestamp});
}
