import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import '../domain/models/video_transcript.dart';

final youtubeRepositoryProvider = Provider<YoutubeRepository>((ref) {
  return YoutubeRepository();
});

class YoutubeRepository {
  final YoutubeExplode _yt = YoutubeExplode();

  Future<List<Video>> searchVideos(String query) async {
    final validVideos = <Video>[];
    try {
      final searchQuery = '$query 中文, cc';
      final results = await _yt.search.search(searchQuery);
      
      final iterator = results.iterator;
      int processedCount = 0;
      
      while (processedCount < 15) {
        Video video;
        try {
          if (!iterator.moveNext()) {
            break;
          }
          video = iterator.current;
        } catch (e) {
          // If a specific video has parsing errors (e.g. viewCount/duration parsing issues on streams), skip it
          debugPrint('Error parsing search result item: $e');
          continue;
        }
        
        processedCount++;
        
        try {
          final manifest = await _yt.videos.closedCaptions.getManifest(video.id);
          final hasChinese = manifest.tracks.any((t) => t.language.code.startsWith('zh'));
          if (hasChinese) {
            validVideos.add(video);
          }
        } catch (_) {
          // No closed captions or error fetching them, skip this video
        }
        
        // Stop early if we have enough results to show a good initial list
        if (validVideos.length >= 6) break;
      }
    } catch (e) {
      debugPrint('Error searching videos for query $query: $e');
    }
    
    return validVideos;
  }

  Future<VideoTranscript?> getTranscript(String videoId) async {
    try {
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);

      final tracks = manifest.tracks;
      if (tracks.isEmpty) return null;

      // Log all available tracks for debugging
      for (final t in tracks) {
        debugPrint('[CC Track] lang=${t.language.code} format=${t.format.formatCode} autoGen=${t.isAutoGenerated}');
      }

      // Priority order: prefer actual Hanzi tracks over auto-generated Pinyin tracks.
      // YouTube auto-generated Chinese captions come in Pinyin (Latin alphabet).
      // The `isAutoGenerated` flag tells us exactly which ones to deprioritize.
      ClosedCaptionTrackInfo? trackInfo;

      // 1. Prefer a MANUAL (not auto-generated) zh track — these contain real Hanzi
      trackInfo = tracks.where((t) =>
        t.language.code.startsWith('zh') && !t.isAutoGenerated
      ).firstOrNull;

      // 2. Fallback: any zh track (may be auto-generated Pinyin, Gemini will convert)
      trackInfo ??= tracks.where((t) => t.language.code.startsWith('zh')).firstOrNull;

      // 3. Fallback: English
      trackInfo ??= tracks.where((t) => t.language.code.startsWith('en')).firstOrNull;

      // 4. Last resort: first available
      trackInfo ??= tracks.first;

      debugPrint('[CC] Selected: lang=${trackInfo.language.code} format=${trackInfo.format.formatCode} autoGen=${trackInfo.isAutoGenerated}');

      final track = await _yt.videos.closedCaptions.get(trackInfo);

      // Detect if the captions are Pinyin (Latin alphabet) or real Hanzi
      final isHanziTrack = track.captions.any((c) => RegExp(r'[\u4e00-\u9fff]').hasMatch(c.text));
      debugPrint('[CC] isHanziTrack=$isHanziTrack, total captions=${track.captions.length}');

      final lines = track.captions.map((c) => TranscriptLine(
        text: c.text,
        // If the captions are Pinyin, store them in the pinyin field immediately
        pinyin: isHanziTrack ? null : c.text,
        start: c.offset,
        duration: c.duration,
      )).toList();

      return VideoTranscript(videoId: videoId, lines: lines);
    } catch (e) {
      debugPrint('Error fetching transcript: $e');
      return null;
    }
  }

  void dispose() {
    _yt.close();
  }
}
