import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:hanzi_master/core/hive_adapter_registry.dart';
import 'package:hanzi_master/features/flashcards/data/models/daily_deck_activity_model.dart';
import 'package:hanzi_master/features/flashcards/data/models/deck_model.dart';
import 'package:hanzi_master/features/flashcards/data/models/flashcard_model.dart';
import 'package:hanzi_master/features/flashcards/data/models/review_stats_model.dart';
import 'package:hanzi_master/features/flashcards/data/repositories/deck_repository_impl.dart';
import 'package:hanzi_master/features/flashcards/data/repositories/flashcard_repository_impl.dart';
import 'package:hanzi_master/features/flashcards/domain/entities/flashcard.dart';
import 'package:hanzi_master/features/media/domain/models/saved_article.dart';
import 'package:hive/hive.dart';

void main() {
  late Directory temporaryDirectory;

  setUp(() async {
    temporaryDirectory =
        await Directory.systemTemp.createTemp('hive-adapters-test-');
    Hive.init(temporaryDirectory.path);
  });

  tearDown(() async {
    await Hive.close();
    await temporaryDirectory.delete(recursive: true);
  });

  test('registers every persisted model under its declared type ID', () {
    registerHiveAdapters();

    expect(Hive.isAdapterRegistered(FlashcardModelAdapter().typeId), isTrue);
    expect(Hive.isAdapterRegistered(DeckModelAdapter().typeId), isTrue);
    expect(Hive.isAdapterRegistered(ReviewStatsModelAdapter().typeId), isTrue);
    expect(Hive.isAdapterRegistered(SavedArticleAdapter().typeId), isTrue);
    expect(Hive.isAdapterRegistered(DailyDeckActivityModelAdapter().typeId),
        isTrue);
  });

  test('replaces a stale adapter occupying the deck type ID', () async {
    Hive.registerAdapter<_StaleDeck>(
      _StaleDeckAdapter(),
      override: true,
    );

    registerHiveAdapters();
    final decks = await Hive.openBox<DeckModel>('decks-with-stale-adapter');
    final deck = DeckModel(
      id: 'default',
      name: 'The Main Library',
      createdAt: DateTime(2026, 9, 6),
    );

    await decks.put(deck.id, deck);

    expect(decks.get('default')?.name, 'The Main Library');
  });

  test('persists the default deck before returning it', () async {
    registerHiveAdapters();
    final decks = await Hive.openBox<DeckModel>('default-deck');
    final repository = DeckRepositoryImpl(decks);

    final result = await repository.getDeckById('default');

    expect(result.isRight(), isTrue);
    expect(decks.get('default')?.name, 'The Main Library');
  });

  test('round-trips decks and daily activity through typed boxes', () async {
    registerHiveAdapters();
    final decks = await Hive.openBox<DeckModel>('decks');
    final activity =
        await Hive.openBox<DailyDeckActivityModel>('daily-activity');

    final deck = DeckModel(
      id: 'hsk1',
      name: 'HSK 1',
      createdAt: DateTime(2026, 9, 6),
    );
    final dailyActivity = DailyDeckActivityModel(
      deckId: 'hsk1',
      dayKey: '2026-09-06@120',
      introducedCardIds: const ['hsk1_001'],
      reviewedCardIds: const [],
      updatedAt: DateTime(2026, 9, 6),
    );
    await decks.put(deck.id, deck);
    await activity.put('today', dailyActivity);

    expect(decks.get('hsk1')?.name, 'HSK 1');
    expect(activity.get('today')?.introducedCardIds, ['hsk1_001']);
  });

  test('creates a deck and persists AI-generated cards into it', () async {
    registerHiveAdapters();
    final decks = await Hive.openBox<DeckModel>('decks');
    final flashcards = await Hive.openBox<FlashcardModel>('flashcards');
    final deckRepository = DeckRepositoryImpl(decks);
    final flashcardRepository = FlashcardRepositoryImpl(flashcards);

    final deckResult = await deckRepository.createDeck(
      'Travel French',
      description: 'Generated by AI',
    );
    final deck = deckResult.fold(
      (error) => fail(error),
      (createdDeck) => createdDeck,
    );
    for (final card in const [
      Flashcard(
        id: 'generated_1',
        deckId: '',
        hanzi: '旅行',
        pinyin: 'lǚxíng',
        definition: 'voyager',
        definitionLanguage: 'French',
        hskLevel: 2,
        strokePaths: [],
        modeStats: {},
      ),
      Flashcard(
        id: 'generated_2',
        deckId: '',
        hanzi: '酒店',
        pinyin: 'jiǔdiàn',
        definition: 'hôtel',
        definitionLanguage: 'French',
        hskLevel: 2,
        strokePaths: [],
        modeStats: {},
      ),
    ]) {
      final saved = await flashcardRepository.saveFlashcard(
        card.copyWith(deckId: deck.id),
      );
      expect(saved.isRight(), isTrue);
    }

    final reloadedDeck = await deckRepository.getDeckById(deck.id);
    final savedCards = await flashcardRepository.getFlashcardsByDeck(deck.id);

    expect(reloadedDeck.isRight(), isTrue);
    expect(
      savedCards.fold((error) => fail(error), (cards) => cards),
      hasLength(2),
    );
  });
}

class _StaleDeckAdapter extends TypeAdapter<_StaleDeck> {
  @override
  final int typeId = 1;

  @override
  _StaleDeck read(BinaryReader reader) => const _StaleDeck();

  @override
  void write(BinaryWriter writer, _StaleDeck obj) {}
}

class _StaleDeck {
  const _StaleDeck();
}
