import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class QAScreen extends ConsumerWidget {
  const QAScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final surfaceColor = isDark ? const Color(0xFF1E1E1E) : Colors.white;
    final bgColor = isDark ? const Color(0xFF121212) : const Color(0xFFFDFCF0);

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        title: const Text("Q&A / FAQ"),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
      ),
      body: ListView(
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
        children: [
          _buildFaqSection(
            title: "Privacy & Data",
            icon: Icons.shield_outlined,
            color: Colors.blue,
            theme: theme,
            surfaceColor: surfaceColor,
            items: [
              _FaqItem(
                question: "Do you keep or store my voice recordings?",
                answer: "No. When you use features like Echo Hall, Scholar's Verdict, or Shadowing Studio, your audio recordings are evaluated securely to generate a pronunciation score and then immediately discarded. We only keep the final numerical rating to track your progress—we do not keep your recording.",
              ),
              _FaqItem(
                question: "What happens to my chat history with the Scholar AI?",
                answer: "Your chat history in Echo Hall is stored locally on your device so you can review past conversations. We do not use your personal conversations to train our AI models.",
              ),
            ],
          ),
          const SizedBox(height: 24),
          _buildFaqSection(
            title: "Audio & Voices",
            icon: Icons.record_voice_over_outlined,
            color: Colors.orange,
            theme: theme,
            surfaceColor: surfaceColor,
            items: [
              _FaqItem(
                question: "Who are the voices speaking in the app?",
                answer: "The voices you hear in AI Stories, Shadowing Studio, and Echo Hall are generated by advanced Neural Text-to-Speech (TTS) models. These are specifically tuned to provide authentic native Chinese accents, appropriate emotional inflection, and natural pacing to help you learn real-world pronunciation.",
              ),
              _FaqItem(
                question: "Why does the Scholar sometimes sound different?",
                answer: "The Scholar dynamically adjusts its speaking style based on the context of the conversation. When acting as a strict tutor, it may speak more slowly and clearly. During casual roleplay (like the Travel Interpreter), it uses a more conversational and natural cadence.",
              ),
              _FaqItem(
                question: "Can I change the gender of the voice?",
                answer: "Currently, our standard AI persona uses a tailored voice to provide the best educational experience. We are exploring adding multiple persona voices in future updates.",
              ),
            ],
          ),
          const SizedBox(height: 24),
          _buildFaqSection(
            title: "Learning & Scoring",
            icon: Icons.school_outlined,
            color: Colors.green,
            theme: theme,
            surfaceColor: surfaceColor,
            items: [
              _FaqItem(
                question: "How does the Pronunciation Rater work?",
                answer: "The app analyzes your speech across three dimensions: Accuracy (did you say the right syllables?), Completeness (did you skip any words?), and Fluency (did you pause naturally and use the right tones?). It compares your audio against native models to generate a score out of 100.",
              ),
              _FaqItem(
                question: "What should I do if the AI mishears me?",
                answer: "If the AI thinks you said something different than intended, it will ask 'Did you mean to say...?'. You can tap the 'Yes, Re-Grade Me!' button in the Pronunciation Report to have the system re-evaluate your original audio against your true intention.",
              ),
            ],
          ),
          const SizedBox(height: 40),
        ],
      ),
    );
  }

  Widget _buildFaqSection({
    required String title,
    required IconData icon,
    required Color color,
    required ThemeData theme,
    required Color surfaceColor,
    required List<_FaqItem> items,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 8.0),
          child: Row(
            children: [
              Icon(icon, color: color, size: 20),
              const SizedBox(width: 8),
              Text(
                title,
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                  color: color,
                ),
              ),
            ],
          ),
        ),
        Container(
          decoration: BoxDecoration(
            color: surfaceColor,
            borderRadius: BorderRadius.circular(16),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withValues(alpha: 0.03),
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          clipBehavior: Clip.antiAlias,
          child: Column(
            children: items.asMap().entries.map((entry) {
              final isLast = entry.key == items.length - 1;
              return Column(
                children: [
                  Theme(
                    data: theme.copyWith(dividerColor: Colors.transparent),
                    child: ExpansionTile(
                      title: Text(
                        entry.value.question,
                        style: const TextStyle(
                          fontWeight: FontWeight.w600,
                          fontSize: 14,
                        ),
                      ),
                      iconColor: color,
                      collapsedIconColor: Colors.grey,
                      childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
                      expandedCrossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          entry.value.answer,
                          style: TextStyle(
                            height: 1.5,
                            fontSize: 14,
                            color: theme.colorScheme.onSurface.withValues(alpha: 0.8),
                          ),
                        ),
                      ],
                    ),
                  ),
                  if (!isLast)
                    Divider(
                      height: 1,
                      indent: 16,
                      endIndent: 16,
                      color: theme.dividerColor.withValues(alpha: 0.1),
                    ),
                ],
              );
            }).toList(),
          ),
        ),
      ],
    );
  }
}

class _FaqItem {
  final String question;
  final String answer;

  _FaqItem({required this.question, required this.answer});
}
