#!/usr/bin/env python3
"""Generate remaining summaries via OpenRouter API for shows not already covered."""
import json, re, time, os, sys
from http.client import HTTPSConnection

base = os.path.dirname(os.path.abspath(__file__))
project = os.path.dirname(base)
dart_path = os.path.join(project, 'lib', 'features', 'media', 'data', 'repositories', 'show_summaries.dart')
shows_path = os.path.join(project, 'lib', 'features', 'media', 'data', 'repositories', 'shows_data.dart')
env_path = os.path.join(project, '.env')

# Load API key
api_key = ''
if os.path.exists(env_path):
    with open(env_path) as f:
        for line in f:
            if line.startswith('OPENROUTER_API_KEY='):
                api_key = line.split('=', 1)[1].strip()
if not api_key:
    print("No API key found")
    exit(1)

# Read existing summaries
existing = set()
if os.path.exists(dart_path):
    with open(dart_path, encoding='utf-8') as f:
        for line in f:
            m = re.search(r"^  '([^']+)':", line)
            if m:
                existing.add(m.group(1))

# Read all raw titles from shows_data.dart
with open(shows_path, encoding='utf-8') as f:
    text = f.read()
lines = text.split('\n')
raw_titles = []
i = 0
while i < len(lines):
    line = lines[i]
    if "'id': 'PL" in line:
        m = re.search(r"'title':\s*'([^']+)'", lines[i+1])
        if m:
            raw_titles.append(m.group(1))
    i += 1

unique_raw = sorted(set(raw_titles))
missing = [t for t in unique_raw if t not in existing]
print(f"Existing: {len(existing)}, Missing: {len(missing)}")

def call_api(prompt):
    conn = HTTPSConnection('openrouter.ai', timeout=60)
    body = json.dumps({
        'model': 'deepseek/deepseek-chat',
        'messages': [
            {'role': 'system', 'content': 'You are a knowledgeable expert on Chinese television dramas. Respond ONLY with a 4-sentence English summary.'},
            {'role': 'user', 'content': prompt}
        ],
        'temperature': 0.7, 'max_tokens': 300,
    })
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {api_key}',
        'HTTP-Referer': 'https://hanzi-master.app',
        'X-Title': 'Hanzi Master',
    }
    try:
        conn.request('POST', '/api/v1/chat/completions', body, headers)
        resp = conn.getresponse()
        raw = resp.read().decode()
        data = json.loads(raw)
        if 'error' in data:
            print(f"  API error: {data['error']}")
            return None
        return data['choices'][0]['message']['content'].strip()
    except Exception as e:
        print(f"  Exception: {e}")
        import traceback
        traceback.print_exc()
        return None

# Generate summaries for missing shows
new_summaries = {}
for idx, title in enumerate(missing):
    try:
        prompt = f'Write a 4-sentence English summary for the Chinese drama: \"{title}\"'
        sys.stdout.write(f"[{idx+1}/{len(missing)}] {title[:60].encode('ascii','replace').decode('ascii')}\n")
        sys.stdout.flush()
        s = call_api(prompt)
        if s:
            new_summaries[title] = s
            sys.stdout.write(f"  OK: {s[:80].encode('ascii','replace').decode('ascii')}...\n")
        else:
            sys.stdout.write("  FAILED\n")
        sys.stdout.flush()
        time.sleep(1)
    except Exception as e:
        sys.stderr.write(f"  SKIP: {e}\n")
        sys.stderr.flush()

# Merge and write
all_summaries = {}
# Read existing
if os.path.exists(dart_path):
    with open(dart_path, encoding='utf-8') as f:
        for line in f:
            m = re.search(r"^  '([^']+)': '([^']*)'", line)
            if m:
                all_summaries[m.group(1)] = m.group(2)
# Add new
all_summaries.update(new_summaries)

# Write
out = [
    '// GENERATED FILE - do not edit manually',
    '// Generated by tools/generate_show_summaries.py',
    '',
    '/// Pre-generated 4-sentence English summaries for each show.',
    '/// Maps show title (exact string from shows_data.dart) -> summary.',
    'const Map<String, String> showSummaries = {',
]
for t in sorted(all_summaries.keys()):
    et = t.replace('\\', '\\\\').replace("'", "\\'")
    es = all_summaries[t].replace('\\', '\\\\').replace("'", "\\'").replace('\n', ' ')
    out.append(f"  '{et}': '{es}',")
out.append('};')
out.append('')

with open(dart_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out))
print(f"\nWritten {len(all_summaries)} total entries")