// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

void main() async {
  final file = File('assets/data/hsk1.json');
  final String contents = await file.readAsString();
  final List<dynamic> words = jsonDecode(contents);

  const Map<String, Map<String, String>> sentenceMap = {
    '爱': {'chinese': '我爱爸爸妈妈。', 'pinyin': 'Wǒ ài bàba māma.', 'english': 'I love mom and dad.'},
    '八': {'chinese': '他有八个苹果。', 'pinyin': 'Tā yǒu bā gè píngguǒ.', 'english': 'He has eight apples.'},
    '爸爸': {'chinese': '我爸爸 is 医生。', 'pinyin': 'Wǒ bàba shì yīshēng.', 'english': 'My dad is a doctor.'},
    '杯子': {'chinese': '这个杯子是我的。', 'pinyin': 'Zhège bēizi shì wǒ de.', 'english': 'This cup is mine.'},
    '北京': {'chinese': '我们住在北京。', 'pinyin': 'Wǒmen zhù zài Běijīng.', 'english': 'We live in Beijing.'},
    '本': {'chinese': '我买了一本书。', 'pinyin': 'Wǒ mǎi le yī běn shū.', 'english': 'I bought a book.'},
    '不客气': {'chinese': '谢谢你！不客气。', 'pinyin': 'Xièxie nǐ! Bú kèqi.', 'english': 'Thank you! You\'re welcome.'},
    '不': {'chinese': '我不喜欢吃苹果。', 'pinyin': 'Wǒ bù xǐhuan chī píngguǒ.', 'english': 'I don\'t like eating apples.'},
    '菜': {'chinese': '我不喜欢吃这个菜。', 'pinyin': 'Wǒ bù xǐhuan chī zhège cài.', 'english': 'I don\'t like to eat this dish.'},
    '茶': {'chinese': '请喝茶。', 'pinyin': 'Qǐng hē chá.', 'english': 'Please drink tea.'},
    '吃': {'chinese': '我们去吃饭吧。', 'pinyin': 'Wǒmen qù chīfàn ba.', 'english': 'Let\'s go eat.'},
    '出租车': {'chinese': '我们坐出租车去。', 'pinyin': 'Wǒmen zuò chūzūchē qù.', 'english': 'We take a taxi to go.'},
    '打电话': {'chinese': '他在打电话。', 'pinyin': 'Tā zài dǎ diànhuà.', 'english': 'He is making a phone call.'},
    '大': {'chinese': '这个苹果很大。', 'pinyin': 'Zhège píngguǒ hěn dà.', 'english': 'This apple is very big.'},
    '的': {'chinese': '这是我的书。', 'pinyin': 'Zhè shì wǒ de shū.', 'english': 'This is my book.'},
    '点': {'chinese': '现在是三点。', 'pinyin': 'Xiànzài shì sān diǎn.', 'english': 'It is three o\'clock now.'},
    '电脑': {'chinese': '我的电脑在桌子上。', 'pinyin': 'Wǒ de diànnǎo zài zhuōzi shàng.', 'english': 'My computer is on the desk.'},
    '电视': {'chinese': '妈妈在看电视。', 'pinyin': 'Māma zài kàn diànshì.', 'english': 'Mom is watching TV.'},
    '电影': {'chinese': '我们去看电影。', 'pinyin': 'Wǒmen qù kàn diànyǐng.', 'english': 'We go to watch a movie.'},
    '东西': {'chinese': '我去商店买东西。', 'pinyin': 'Wǒ qù shāngdiàn mǎi dōngxi.', 'english': 'I go to the store to buy things.'},
    '都': {'chinese': '我们都是学生。', 'pinyin': 'Wǒmen dōu shì xuésheng.', 'english': 'We are all students.'},
    '读': {'chinese': '你喜欢读书吗？', 'pinyin': 'Nǐ xǐhuan dú shū ma?', 'english': 'Do you like to read books?'},
    '对不起': {'chinese': '对不起。没关系。', 'pinyin': 'Duìbuqǐ. Méi guānxi.', 'english': 'Sorry. It\'s okay.'},
    '多': {'chinese': '这里的人很多。', 'pinyin': 'Zhèlǐ de rén hěn duō.', 'english': 'There are many people here.'},
    '多少': {'chinese': '这个多少钱？', 'pinyin': 'Zhège duōshao qián?', 'english': 'How much is this?'},
    '儿子': {'chinese': '她儿子三岁了。', 'pinyin': 'Tā érzi sān suì le.', 'english': 'Her son is three years old.'},
    '二': {'chinese': '现在是两点二十分。', 'pinyin': 'Xiànzài shì liǎng diǎn èr shí fēn.', 'english': 'It\'s 2:20 now.'},
    '饭馆': {'chinese': '我们去饭馆吃饭。', 'pinyin': 'Wǒmen qù fànguǎn chī fàn.', 'english': 'We go to the restaurant to eat.'},
    '飞机': {'chinese': '他坐飞机去北京。', 'pinyin': 'Tā zuò fēijī qù Běijīng.', 'english': 'He takes a plane to Beijing.'},
    '分钟': {'chinese': '我等了十分钟。', 'pinyin': 'Wǒ děng le shí fēnzhōng.', 'english': 'I waited for 10 minutes.'},
    '高兴': {'chinese': '认识你很高兴。', 'pinyin': 'Rènshi nǐ hěn gāoxìng.', 'english': 'Glad to meet you.'},
    '个': {'chinese': '我有一个苹果。', 'pinyin': 'Wǒ yǒu yí gè píngguǒ.', 'english': 'I have an apple.'},
    '工作': {'chinese': '他在医院工作。', 'pinyin': 'Tā zài yīyuàn gōngzuò.', 'english': 'He works at the hospital.'},
    '狗': {'chinese': '我有一只小狗。', 'pinyin': 'Wǒ yǒu yì zhī xiǎo gǒu.', 'english': 'I have a small dog.'},
    '汉语': {'chinese': '他在学习汉语。', 'pinyin': 'Tā zài xuéxí Hànyǔ.', 'english': 'He is learning Chinese.'},
    '好': {'chinese': '今天天气很好。', 'pinyin': 'Jīntiān tiānqì hěn hǎo.', 'english': 'The weather is very good today.'},
    '号': {'chinese': '今天是五月一号。', 'pinyin': 'Jīntiān shì wǔ yuè yī hào.', 'english': 'Today is May 1st.'},
    '喝': {'chinese': '你想喝水吗？', 'pinyin': 'Nǐ xiǎng hē shuǐ ma?', 'english': 'Do you want to drink water?'},
    '和': {'chinese': '我和你一起去。', 'pinyin': 'Wǒ hé nǐ yìqǐ qù.', 'english': 'I will go with you.'},
    '很': {'chinese': '我很喜欢中国。', 'pinyin': 'Wǒ hěn xǐhuan Zhōngguó.', 'english': 'I really like China.'},
    '后面': {'chinese': '狗在房子后面。', 'pinyin': 'Gǒu zài fángzi hòumiàn.', 'english': 'The dog is behind the house.'},
    '回': {'chinese': '他五点回家。', 'pinyin': 'Tā wǔ diǎn huí jiā.', 'english': 'He goes home at 5 o\'clock.'},
    '会': {'chinese': '我会说汉语。', 'pinyin': 'Wǒ huì shuō Hànyǔ.', 'english': 'I can speak Chinese.'},
    '几': {'chinese': '你有几个苹果？', 'pinyin': 'Nǐ yǒu jǐ gè píngguǒ?', 'english': 'How many apples do you have?'},
    '家': {'chinese': '我家在北京。', 'pinyin': 'Wǒ jiā zài Běijīng.', 'english': 'My home is in Beijing.'},
    '叫': {'chinese': '你叫什么名字？', 'pinyin': 'Nǐ jiào shénme míngzi?', 'english': 'What is your name?'},
    '今天': {'chinese': '今天天气很好。', 'pinyin': 'Jīntiān tiānqì hěn hǎo.', 'english': 'The weather is very good today.'},
    '九': {'chinese': '现在是九点。', 'pinyin': 'Xiànzài shì jiǔ diǎn.', 'english': 'It\'s nine o\'clock now.'},
    '开': {'chinese': '他会开汽车。', 'pinyin': 'Tā huì kāi qìchē.', 'english': 'He can drive a car.'},
    '看': {'chinese': '他在看书。', 'pinyin': 'Tā zài kàn shū.', 'english': 'He is reading a book.'},
    '看见': {'chinese': '我看见他了。', 'pinyin': 'Wǒ kànjiàn tā le.', 'english': 'I saw him.'},
    '块': {'chinese': '这个十块钱。', 'pinyin': 'Zhège shí kuài qián.', 'english': 'This is 10 yuan.'},
    '来': {'chinese': '他昨天来我家了。', 'pinyin': 'Tā zuótiān lái wǒ jiā le.', 'english': 'He came to my house yesterday.'},
    '老师': {'chinese': '王老师在学校。', 'pinyin': 'Wáng lǎoshī zài xuéxiào.', 'english': 'Teacher Wang is at school.'},
    '了': {'chinese': '我吃饭了。', 'pinyin': 'Wǒ chīfàn le.', 'english': 'I have eaten.'},
    '冷': {'chinese': '今天很冷。', 'pinyin': 'Jīntiān hěn lěng.', 'english': 'It is very cold today.'},
    '里': {'chinese': '猫在衣服里。', 'pinyin': 'Māo zài yīfu lǐ.', 'english': 'The cat is inside the clothes.'},
    '零': {'chinese': '现在是两点零五分。', 'pinyin': 'Xiànzài shì liǎng diǎn líng wǔ fēn.', 'english': 'It is 2:05 now.'},
    '六': {'chinese': '我有六本书。', 'pinyin': 'Wǒ yǒu liù běn shū.', 'english': 'I have six books.'},
    '妈妈': {'chinese': '我妈妈是老师。', 'pinyin': 'Wǒ māma shì lǎoshī.', 'english': 'My mother is a teacher.'},
    '吗': {'chinese': '你是学生吗？', 'pinyin': 'Nǐ shì xuésheng ma?', 'english': 'Are you a student?'},
    '买': {'chinese': '我想买杯子。', 'pinyin': 'Wǒ xiǎng mǎi bēizi.', 'english': 'I want to buy a cup.'},
    '猫': {'chinese': '这只猫很漂亮。', 'pinyin': 'Zhè zhī māo hěn piàoliang.', 'english': 'This cat is very pretty.'},
    '没': {'chinese': '我没去北京。', 'pinyin': 'Wǒ méi qù Běijīng.', 'english': 'I didn\'t go to Beijing.'},
    '米饭': {'chinese': '我不爱吃米饭。', 'pinyin': 'Wǒ bú ài chī mǐfàn.', 'english': 'I don\'t like to eat rice.'},
    '明天': {'chinese': '我明天去学校。', 'pinyin': 'Wǒ míngtiān qù xuéxiào.', 'english': 'I\'ll go to school tomorrow.'},
    '名字': {'chinese': '你叫什么名字？', 'pinyin': 'Nǐ jiào shénme míngzi?', 'english': 'What is your name?'},
    '哪': {'chinese': '你是哪国人？', 'pinyin': 'Nǐ shì nǎ guó rén?', 'english': 'Which country are you from?'},
    '哪儿': {'chinese': '你在哪儿工作？', 'pinyin': 'Nǐ zài nǎr gōngzuò?', 'english': 'Where do you work?'},
    '那': {'chinese': '那是一个苹果。', 'pinyin': 'Nà shì yí gè píngguǒ.', 'english': 'That is an apple.'},
    '那儿': {'chinese': '我的书在那儿。', 'pinyin': 'Wǒ de shū zài nàr.', 'english': 'My book is over there.'},
    '呢': {'chinese': '我是学生，你呢？', 'pinyin': 'Wǒ shì xuésheng, nǐ ne?', 'english': 'I am a student, and you?'},
    '能': {'chinese': '我能坐这儿吗？', 'pinyin': 'Wǒ néng zuò zhèr ma?', 'english': 'Can I sit here?'},
    '你': {'chinese': '你好！', 'pinyin': 'Nǐ hǎo!', 'english': 'Hello!'},
    '年': {'chinese': '我是去年去北京的。', 'pinyin': 'Wǒ shì qùnián qù Běijīng de.', 'english': 'I went to Beijing last year.'},
    '女儿': {'chinese': '我有两个女儿。', 'pinyin': 'Wǒ yǒu liǎng gè nǚ\'ér.', 'english': 'I have two daughters.'},
    '朋友': {'chinese': '他是我的好朋友。', 'pinyin': 'Tā shì wǒ de hǎo péngyou.', 'english': 'He is my good friend.'},
    '漂亮': {'chinese': '你的衣服很漂亮。', 'pinyin': 'Nǐ de yīfu hěn piàoliang.', 'english': 'Your clothes are very pretty.'},
    '苹果': {'chinese': '你想吃苹果吗？', 'pinyin': 'Nǐ xiǎng chī píngguǒ ma?', 'english': 'Do you want to eat an apple?'},
    '七': {'chinese': '他有七块钱。', 'pinyin': 'Tā yǒu qī kuài qián.', 'english': 'He has 7 yuan.'},
    '钱': {'chinese': '这个杯子多少钱？', 'pinyin': 'Zhège bēizi duōshao qián?', 'english': 'How much money is this cup?'},
    '前面': {'chinese': '猫在前面。', 'pinyin': 'Māo zài qiánmiàn.', 'english': 'The cat is in the front.'},
    '请': {'chinese': '请坐。', 'pinyin': 'Qǐng zuò.', 'english': 'Please sit.'},
    '去': {'chinese': '我明天去北京。', 'pinyin': 'Wǒ míngtiān qù Běijīng.', 'english': 'I will go to Beijing tomorrow.'},
    '热': {'chinese': '今天天气很热。', 'pinyin': 'Jīntiān tiānqì hěn rè.', 'english': 'The weather is very hot today.'},
    '人': {'chinese': '商店里有很多人。', 'pinyin': 'Shāngdiàn lǐ yǒu hěn duō rén.', 'english': 'There are many people in the store.'},
    '认识': {'chinese': '认识你很高兴。', 'pinyin': 'Rènshi nǐ hěn gāoxìng.', 'english': 'Glad to meet you.'},
    '日': {'chinese': '今天是五月三日。', 'pinyin': 'Jīntiān shì wǔ yuè sān rì.', 'english': 'Today is May 3rd.'},
    '三': {'chinese': '我有三本书。', 'pinyin': 'Wǒ yǒu sān běn shū.', 'english': 'I have three books.'},
    '商店': {'chinese': '我去商店买东西。', 'pinyin': 'Wǒ qù shāngdiàn mǎi dōngxi.', 'english': 'I go to the store to buy things.'},
    '上': {'chinese': '杯子在桌子上。', 'pinyin': 'Bēizi zài zhuōzi shàng.', 'english': 'The cup is on the table.'},
    '上午': {'chinese': '我上午在学校。', 'pinyin': 'Wǒ shàngwǔ zài xuéxiào.', 'english': 'I am at school in the morning.'},
    '少': {'chinese': '这里的人很少。', 'pinyin': 'Zhèlǐ de rén hěn shǎo.', 'english': 'There are few people here.'},
    '谁': {'chinese': '那个人是谁？', 'pinyin': 'Nà gè rén shì shéi?', 'english': 'Who is that person?'},
    '什么': {'chinese': '你叫什么名字？', 'pinyin': 'Nǐ jiào shénme míngzi?', 'english': 'What is your name?'},
    '十': {'chinese': '现在是十点。', 'pinyin': 'Xiànzài shì shí diǎn.', 'english': 'It\'s ten o\'clock now.'},
    '时候': {'chinese': '你什么时候回家？', 'pinyin': 'Nǐ shénme shíhou huí jiā?', 'english': 'When will you go home?'},
    '是': {'chinese': '我是学生。', 'pinyin': 'Wǒ shì xuésheng.', 'english': 'I am a student.'},
    '书': {'chinese': '我喜欢看书。', 'pinyin': 'Wǒ xǐhuan kàn shū.', 'english': 'I like reading books.'},
    '水': {'chinese': '我想喝水。', 'pinyin': 'Wǒ xiǎng hē shuǐ.', 'english': 'I want to drink water.'},
    '水果': {'chinese': '我喜欢吃水果。', 'pinyin': 'Wǒ xǐhuan chī shuǐguǒ.', 'english': 'I like eating fruit.'},
    '睡觉': {'chinese': '他去睡觉了。', 'pinyin': 'Tā qù shuìjiào le.', 'english': 'He went to sleep.'},
    '说话': {'chinese': '他们在说话。', 'pinyin': 'Tāmen zài shuōhuà.', 'english': 'They are talking.'},
    '四': {'chinese': '我有四个苹果。', 'pinyin': 'Wǒ yǒu sì gè píngguǒ.', 'english': 'I have four apples.'},
    '岁': {'chinese': '我儿子三岁了。', 'pinyin': 'Wǒ érzi sān suì le.', 'english': 'My son is 3 years old.'},
    '他': {'chinese': '他是我的老师。', 'pinyin': 'Tā shì wǒ de lǎoshī.', 'english': 'He is my teacher.'},
    '她': {'chinese': '她是我的朋友。', 'pinyin': 'Tā shì wǒ de péngyou.', 'english': 'She is my friend.'},
    '太': {'chinese': '这个苹果太大了。', 'pinyin': 'Zhège píngguǒ tài dà le.', 'english': 'This apple is too big.'},
    '天气': {'chinese': '今天天气很好。', 'pinyin': 'Jīntiān tiānqì hěn hǎo.', 'english': 'The weather is very good today.'},
    '听': {'chinese': '你喜欢听什么？', 'pinyin': 'Nǐ xǐhuan tīng shénme?', 'english': 'What do you like to listen to?'},
    '同学': {'chinese': '他们是我的同学。', 'pinyin': 'Tāmen shì wǒ de tóngxué.', 'english': 'They are my classmates.'},
    '喂': {'chinese': '喂，你在哪儿？', 'pinyin': 'Wéi, nǐ zài nǎr?', 'english': 'Hello (on phone), where are you?'},
    '我': {'chinese': '我是一个学生。', 'pinyin': 'Wǒ shì yí gè xuésheng.', 'english': 'I am a student.'},
    '我们': {'chinese': '我们是好朋友。', 'pinyin': 'Wǒmen shì hǎo péngyou.', 'english': 'We are good friends.'},
    '五': {'chinese': '现在是五点。', 'pinyin': 'Xiànzài shì wǔ diǎn.', 'english': 'It is five o\'clock.'},
    '喜欢': {'chinese': '我喜欢学汉语。', 'pinyin': 'Wǒ xǐhuan xué Hànyǔ.', 'english': 'I like learning Chinese.'},
    '下': {'chinese': '猫在桌子下。', 'pinyin': 'Māo zài zhuōzi xià.', 'english': 'The cat is under the table.'},
    '下午': {'chinese': '我下午去商店。', 'pinyin': 'Wǒ xiàwǔ qù shāngdiàn.', 'english': 'I go to the store in the afternoon.'},
    '下雨': {'chinese': '今天下雨了。', 'pinyin': 'Jīntiān xià yǔ le.', 'english': 'It rained today.'},
    '先生': {'chinese': '王先生在打电话。', 'pinyin': 'Wáng xiānsheng zài dǎ diànhuà.', 'english': 'Mr. Wang is on the phone.'},
    '现在': {'chinese': '现在几点？', 'pinyin': 'Xiànzài jǐ diǎn?', 'english': 'What time is it now?'},
    '想': {'chinese': '我想去北京。', 'pinyin': 'Wǒ xiǎng qù Běijīng.', 'english': 'I want to go to Beijing.'},
    '小': {'chinese': '这只狗很小。', 'pinyin': 'Zhè zhī gǒu hěn xiǎo.', 'english': 'This dog is very small.'},
    '小姐': {'chinese': '王小姐是老师。', 'pinyin': 'Wáng xiǎojie shì lǎoshī.', 'english': 'Miss Wang is a teacher.'},
    '些': {'chinese': '我买了些苹果。', 'pinyin': 'Wǒ mǎi le xiē píngguǒ.', 'english': 'I bought some apples.'},
    '写': {'chinese': '我会写汉字。', 'pinyin': 'Wǒ huì xiě Hànzì.', 'english': 'I can write Chinese characters.'},
    '谢谢': {'chinese': '谢谢你！', 'pinyin': 'Xièxie nǐ!', 'english': 'Thank you!'},
    '星期': {'chinese': '一个星期有七天。', 'pinyin': 'Yí gè xīngqī yǒu qī tiān.', 'english': 'A week has seven days.'},
    '学生': {'chinese': '我们都是学生。', 'pinyin': 'Wǒmen dōu shì xuésheng.', 'english': 'We are all students.'},
    '学习': {'chinese': '他在学习汉语。', 'pinyin': 'Tā zài xuéxí Hànyǔ.', 'english': 'He is studying Chinese.'},
    '学校': {'chinese': '我们明天去学校。', 'pinyin': 'Wǒmen míngtiān qù xuéxiào.', 'english': 'We go to school tomorrow.'},
    '衣服': {'chinese': '我在商店买衣服。', 'pinyin': 'Wǒ zài shāngdiàn mǎi yīfu.', 'english': 'I buy clothes in the store.'},
    '医生': {'chinese': '他是一个医生。', 'pinyin': 'Tā shì yí gè yīshēng.', 'english': 'He is a doctor.'},
    '医院': {'chinese': '他在医院 work。', 'pinyin': 'Tā zài yīyuàn gōngzuò.', 'english': 'He works at a hospital.'},
    '椅子': {'chinese': '小狗在椅子下。', 'pinyin': 'Xiǎo gǒu zài yǐzi xià.', 'english': 'The little dog is under the chair.'},
    '再见': {'chinese': '再见，明天见。', 'pinyin': 'Zàijiàn, míngtiān jiàn.', 'english': 'Goodbye, see you tomorrow.'},
    '怎么': {'chinese': '这个字怎么读？', 'pinyin': 'Zhège zì zěnme dú?', 'english': 'How do you read this character?'},
    '怎么样': {'chinese': '今天天气怎么样？', 'pinyin': 'Jīntiān tiānqì zěnmeyàng?', 'english': 'How is the weather today?'},
    '这': {'chinese': '这是一个杯子。', 'pinyin': 'Zhè shì yí gè bēizi.', 'english': 'This is a cup.'},
    '这儿': {'chinese': '你住在这儿吗？', 'pinyin': 'Nǐ zhù zài zhèr ma?', 'english': 'Do you live here?'},
    '中国': {'chinese': '他在中国工作。', 'pinyin': 'Tā zài Zhōngguó gōngzuò.', 'english': 'He works in China.'},
    '中午': {'chinese': '我中午去吃饭。', 'pinyin': 'Wǒ zhōngwǔ qù chī fàn.', 'english': 'I will go eat at noon.'},
    '住': {'chinese': '我住在北京。', 'pinyin': 'Wǒ zhù zài Běijīng.', 'english': 'I live in Beijing.'},
    '桌子': {'chinese': '书在桌子上。', 'pinyin': 'Shū zài zhuōzi shàng.', 'english': 'The book is on the table.'},
    '字': {'chinese': '这个字我不认识。', 'pinyin': 'Zhège zì wǒ bú rènshi.', 'english': 'I don\'t know this character.'},
    '昨天': {'chinese': '他昨天没去学校。', 'pinyin': 'Tā zuótiān méi qù xuéxiào.', 'english': 'He didn\'t go to school yesterday.'},
    '坐': {'chinese': '请坐。', 'pinyin': 'Qǐng zuò.', 'english': 'Please sit.'},
    '做': {'chinese': '你在做什么？', 'pinyin': 'Nǐ zài zuò shénme?', 'english': 'What are you doing?'}
  };

  final List<dynamic> updatedWords = words.map((word) {
    final String hanzi = word['hanzi'];
    final Map<String, dynamic> newWord = Map<String, dynamic>.from(word);
    
    if (sentenceMap.containsKey(hanzi)) {
      newWord['example_sentence'] = sentenceMap[hanzi]!['chinese'];
      newWord['example_pinyin'] = sentenceMap[hanzi]!['pinyin'];
      newWord['example_english'] = sentenceMap[hanzi]!['english'];
    } else {
      newWord['example_sentence'] = '这是$hanzi。';
      newWord['example_pinyin'] = 'Zhè shì $hanzi.';
      newWord['example_english'] = 'This is $hanzi.';
    }
    return newWord;
  }).toList();

  const jsonOutput = JsonEncoder.withIndent('  ');
  final String encoded = jsonOutput.convert(updatedWords);
  await File('assets/data/hsk1_sentences.json').writeAsString(encoded);
  print('Done! Saved to assets/data/hsk1_sentences.json');
}
